# Generated by Django 4.1.7 on 2023-04-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Palco', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instrument',
            new_name='Instrumento',
        ),
        migrations.RenameField(
            model_name='instrumento',
            old_name='nome',
            new_name='nomeInstrumento',
        ),
    ]
