# Generated by Django 4.1.7 on 2023-04-01 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Palco', '0002_rename_instrument_instrumento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='modelo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
