# Generated by Django 4.1.7 on 2023-04-01 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Palco', '0003_instrumento_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='nomeInstrumento',
        ),
    ]
